version: '3'

services: 
    clickhouse-server:
        image: yandex/clickhouse-server
        container_name: clickhouse-server
        expose:
            - "9000"
        user: root
        privileged: true
        ports:
            - "8133:8123"
            - "9011:9000"
        volumes: 
            - ./some_clickhouse_database:/var/lib/clickhouse
        ulimits: 
            nofile:
                soft: 262144
                hard: 262144
    
    # 图形化界面
    # tabix:
    #     image: spoonest/clickhouse-tabix-web-client
    #     ports: 
    #         - 8080:80
    #     environment: 
    #         - CH_NAME='myco' 
    #         - CH_HOST='clickhouse-server:8123'

