version: '2'

services:
  #Service for nameserver
  namesrv:
    image: apacherocketmq/rocketmq:4.7.1
    container_name: rmqnamesrv
    ports:
      - 9876:9876
      - 10901:10911
      - 10902:10912
    volumes:
      - ./tmp/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv

  #Service for broker
  broker1:
    image: apacherocketmq/rocketmq:4.7.1
    container_name: rmqbroker-1
    depends_on: 
      - namesrv
    links:
      - namesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./tmp/broker1/logs:/home/rocketmq/logs
      - ./tmp/broker1/store:/home/rocketmq/store
      - ./data/broker/conf/broker.conf:/opt/rocketmq-4.5.0/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-4.5.0/conf/broker.conf

  #Service for another broker -- broker1
  broker2:
    image: apacherocketmq/rocketmq:4.7.1
    container_name: rmqbroker-2
    depends_on: 
      - namesrv
    links:
      - namesrv
    ports:
      - 10929:10909
      - 10931:10911
      - 10932:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./tmp/broker2/logs:/home/rocketmq/logs
      - ./tmp/broker2/store:/home/rocketmq/store
      - ./data1/broker/conf/broker.conf:/opt/rocketmq-4.5.0/conf/broker.conf
    command: sh mqbroker -c /opt/rocketmq-4.5.0/conf/broker.conf
  
  # 控制台
  console:
    image: apacherocketmq/rocketmq-console:2.0.0
    container_name: rocketmq-console
    depends_on: 
      - namesrv
    links:
      - namesrv
    ports: 
      - 8080:8080
    environment: 
      - JAVA_OPTS=-Drocketmq.namesrv.addr=namesrv:9876 
      - -Dcom.rocketmq.sendMessageWithVIPChannel=false